# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sinclair Gurny
title: Looking for a Software Engineering Position
email: sinclairg@hotmail.com

darkmode: false

# Social links
github_username:  SinclairGurny
linkedin_username: sinclair-gurny

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Sinclair and I like making things. Currently a 5th year coterminal student at Rensselaer Polytechnic Institute finishing my M.S in Computer Science. I finished my B.S. in Computer Science and Cognitive Science in May 2020.

<bold>Certifications:</bold>
  - Wilderness First Aid (Stonehearth Open Learning Opportunities (SOLO) Wilderness Medicine) [Oct 2019-Oct 2021]
  - CPR (Stonehearth Open Learning Opportunities (SOLO))

''Awards:''
  - Jack Hollingsworth Prize (May 2019) This prize is awarded to one computer science student a year who made a contribution to the education program at Rensselaer.
  - Founder's Award of Excellence (Oct 2019) This prize is given to students who emody qualities of creativity, discovery, leadership, and the value of pride and responsibility.

# Education Section
educaton_title: Education

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

  Some of my other hobbies are:
    - Fixed-gear Cycling
    - Roller-blading
    - Robotics
    - Electronics (Building computers from parts I find)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
