# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sinclair Gurny
title: Machine Learning Engineer
email: sinclairgurny@gmail.com

# Social links
github_username:  SinclairGurny
linkedin_username: sinclair-gurny

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I'm Sinclair. I am currently working as a Machine Learning Engineer and Infrastructure Engineer at Stonewall Defense.
  
  During my 5 year coterminal program at Rensselaer Polytechnic Institute I completed my M.S. in Computer Science in May 2020 and my B.S. in Computer Science and Cognitive Science in May 2019.
  
  My thesis "Learning Models from Avionics Data Streams" focuses on using declarative machine learning to create a data-driven system which can estimate aircraft weight in real-time during take-off. It is the only system which uses no external sensors and does real time estimation before leaving the runway making it capable of preventing accidents such as overrunning the runway. My paper based on my thesis work was accepted into the Digital Avionics Systems Conference (DASC) 2020, titled "Aircraft Weight Estimation During Take-off Using Declarative Machine Learning". My publications can be found [here](https://wcl.cs.rpi.edu/bib/Author/GURNY-S.html).
  
  Certifications
  - Wilderness First Aid&#58; (Stonehearth Open Learning Opportunities) \[Oct 2019-Oct 2021\]
  - CPR&#58; (Stonehearth Open Learning Opportunities) \[Oct 2019-Oct 2021\]
  
  Awards
  - Jack Hollingsworth Prize (May 2019)&#58; This prize is awarded to one computer science student a year who made a contribution to the education program at Rensselaer.
  - Founder's Award of Excellence (Oct 2019)&#58; This prize is given to less than 1% of students who emody qualities of creativity, discovery, leadership, and the value of pride and responsibility.
  
  Programming Languages
  - Python
  - Bash
  - C/C++
  - Java/Scala
  - Julia
  - Lisp (Emacs Lisp/Scheme/Racket)
  
  Skills
  - Deep Learning (PyTorch)
  - Visualization (plotly, matplotlib, seaborn), Dashboard (streamlit)
  - Machine Learning and Data Science (numpy, scipy, pandas, xgboost, lightgbm) [Kaggle profile](https://www.kaggle.com/sinclairg)
  - API development (FastAPI, flask)
  - AWS (EC2, Lambda, S3, EKS, Athena, Glue)
  - Kubernetes
  - Docker, Docker Compose


# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
education_title: Education

# More Section
more_title: A Little More About Me
more_content: |
  Learning and improving is my true passion.
  
  I use GNU Emacs because I love the customizability, and how it does everything all in one place. My favorite emacs packages are magit, frog-jump-buffer, org and org-roam. And no I do not use evil mode.
  
  I currently use the [Soul](https://kennetchaz.github.io/symmetric-typing/soul.html) keyboard layout (very similar to Colemak) because it was a fun challenge to fight with my typing muscle memory and also improve the ergonomics of typing. A bunch of small improvements to your daily workflow add up in the long run.
  
  I am also an avid [Shogi](https://www.shogi.or.jp/event/english-pamphlet.pdf) player (Japanese chess) and captain a shogi team which won our division in 2021. Shogi is unique when compared to chess in that captured pieces can be placed back on the board.
  
  Besides that I enjoy biking and I am learning to play classical guitar.

# Footer
footer_show_references: true

# Build settings
darkmode: false
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
