# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sinclair Gurny
title: Looking for a Software Engineering Position
email: sinclairg@hotmail.com

# Social links
github_username:  SinclairGurny
linkedin_username: sinclair-gurny

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I'm Sinclair and I like making things. 
  Currently a 5th year coterminal student at Rensselaer Polytechnic Institute finishing my M.S in Computer Science. 
  My interests are artificial intelligence, robotics, aerospace, and electronics. 
  I was fortunate to be able to combine many of my interests in my thesis&#58; "Learning Models from Avionics Data Streams". 
  It focuses on using declarative machine learning to create a data-driven system which can estimate aircraft weight in real-time during take-off.
  The goal was to be able to prevent aircraft accidents caused by overweight conditions.

  I finished my B.S. in Computer Science and Cognitive Science in May 2019. 
  I am currently looking for a full-time software engineering position starting Summer 2020.
  
  Certifications
  - Wilderness First Aid&#58; (Stonehearth Open Learning Opportunities) \[Oct 2019-Oct 2021\]
  - CPR&#58; (Stonehearth Open Learning Opportunities) \[Oct 2019-Oct 2021\]
  
  Awards
  - Jack Hollingsworth Prize (May 2019)&#58; This prize is awarded to one computer science student a year who made a contribution to the education program at Rensselaer.
  - Founder's Award of Excellence (Oct 2019)&#58; This prize is given to students who emody qualities of creativity, discovery, leadership, and the value of pride and responsibility.
  
  Programming Languages
  - C/C++
  - Java
  - Python
  - Scala
  - Scheme/Racket
  - Lua
  
  Skills
  - Microsoft Office
  - CAD
  - Git
  - Video Editing
  - Windows and UNIX OSes
  - Virtual Machines
  - Distributed and Concurrent Programming

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: |
  Learning is my true passion. I aim to learn as many new skills as possible.
  I love computers and I repair old computer I find. I also love to be outside and go cycling or hiking.
  

# Footer
footer_show_references: true

# Build settings
darkmode: false
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
